### ISSUE TITLE
Copy or clone method for SelectoBuilder

### ISSUE THREAD

**Issue by isaacgg** [mongo-dart/mongo_dart_query#20]
Hello, first of all, thanks for this library. This is an amazing work!

My question is: is there any way I can clone or copy a SelectorBuilder?
I have a list of these, and all I can get is the reference of these objects. I have tried several ways, but dart has no easy way to clone objects unless its already instantiated in the class.
I have post a [question](https://stackoverflow.com/questions/58894256/when-using-list-or-map-flutter-keeps-passing-a-reference-but-i-need-a-copy) related to this problem in SO with no luck.

**Comment by Mehmetyaz** [comment]
#21 added

**Comment by giorgiofran** [comment]
I close this issue. Feel free to re-open it if needed.
